export enum EPlantClass {
	Indoor = 'Комнатное',
	Garden = 'Садовое',
}

export enum EPlantSubclass {
	Shrubs = 'Кустарники',
	Conifers = 'Хвойные',
	Ferns = 'Папоротники',
	Orchids = 'Орхидеи',
	Annuals = 'Однолетние',
	Perennials = 'Многолетники',
	Bulbs = 'Лампочки',
	Cacti = 'Кактусы, суккуленты',
	Trees = 'Деревья',
	Grass = 'Декоративная трава',
	Alpine = 'Альпинисты',
}

export enum EPlantType {
	Aloe = 'Алоэ',
	Cactus = 'Кактус',
	Succulent = 'Суккулент',
	Marigold = 'Бархатцы',
	Verbena = 'Вербена',
	Geranium = 'Герань',
	Hyacinth = 'Гиацинт',
	Wisteria = 'Глициния',
	Grass = 'Декоративная трава',
	Oak = 'Дуб',
	Spruce = 'Ель',
	Honeysuckle = 'Жимолость',
	Iris = 'Ирис',
	Clematis = 'Клематис',
	Maple = 'Клен',
	Cosmos = 'Космея',
	Lilies = 'Лилии',
	Juniper = 'Можжевельник',
	Monarda = 'Монарда',
	Narcissus = 'Нарцисс',
	Orchid = 'Орхидея',
	Ferns = 'Папоротники',
	Peony = 'Пион',
	Ivy = 'Плющ',
	Rhododendron = 'Рододендрон',
	Sansevieria = 'Сансевиерия',
	Pine = 'Сосна',
	Tulip = 'Тюльпан',
	Zinnia = 'Циния',
	Apple = 'Яблоня',
	Echinacea = 'Эхинацея',
}
